---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
 - name: ubuntu-12.04
   driver:
     box: hashicorp/precise64
     customize:
       memory: 2048
     network :
       -  ["private_network", {ip: "192.168.33.34" }]
  #- name: centos-7
   # driver:
    #  box: centos/7
     # network :
      #-  ["private_network", {ip: "192.168.33.33" }]

suites:
  - name: default
    run_list:
      - recipe[orangehrm::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
