---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  #- name: ubuntu-14.04
    #driver: 
     # box: ubuntu/trusty64
      #network:
       # - ["private_network", {ip: "192.168.33.100"}]
  - name: centos-7
    driver: 
      box: centos/7
      network:
        - ["private_network", {ip: "192.168.33.100"}]

suites:
  - name: default
    run_list:
      - recipe[bettercookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
