---
- name: install tomcat on ubuntu server
  hosts: appservers
  become: yes
  tasks:
    - name: update packages and install java
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present
    - name: Ensure group tomcat exists
      ansible.builtin.group:
        name: "{{ tomcat_system_groupname }}"
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_system_username }}"
        system: yes
        create_home: yes
        group: "{{ tomcat_system_groupname }}"
        home: "{{ tomcat_homedir }}"
        shell: "{{ tomcat_shell }}"
    - name: check if it is necessary to download tomcat
      ansible.builtin.stat:
        path: "{{ tomcat_homedir }}/{{ tomcat_version }}"
      register: version_stat
    - name: print version_stat
      debug:
        var: version_stat
    - name: download tomcat
      ansible.builtin.unarchive:
        src: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_homedir }}"
        remote_src: yes
        owner: "{{ tomcat_system_username }}"
        group: "{{ tomcat_system_groupname }}"
        extra_opts:
          - --strip-components=1
      when: version_stat.stat.exists == false
    - name: Find script files
      ansible.builtin.find:
        paths: "{{ tomcat_homedir }}/bin/"
        patterns: '*.sh'
      register: script_files
    - name: changing shell file permissions
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0753'
      loop: "{{ script_files.files }}"
      notify:
        - create work done file
  handlers:
    - name: create work done file
      ansible.builtin.file:
        path: "{{ tomcat_homedir }}/{{ tomcat_version }}"
        state: "touch"
    
